name: Build

on:
  workflow_dispatch:
    inputs:
     environment:
        type: environment
        description: Select the environment

permissions:
  id-token: write
  contents: write
  packages: write
  pull-requests: write
  actions: read

jobs:
 build:
   runs-on: ubuntu-latest
   environment: ${{ inputs.environment }}
   timeout-minutes: 30
   steps:
     - name: build
       run: |
         echo ${{ vars.ENV}}
